### ISSUE TITLE
Allow modifying .prettierrc.json

### ISSUE THREAD

**Issue by xChickens** [exuanbo/ts-standardx#17]
Hi, appreciate this package because it's basically what i'm looking for (standardx for Typescript), but I found that in ts-standard, they recently added prettier to the package (version 9.0.0, Dec 06, 2020) and it causes a number of eslint rule changes to not work because of conflicts with the prettier config. Is it possible for you to allow changes to the prettierrc? Thanks!

**Comment by exuanbo** [comment]
Hi,

I also noticed the conflicts, so in https://github.com/exuanbo/ts-standardx/blob/main/src/compatRules.ts I hand-picked the conflicted rules and tested them in https://github.com/exuanbo/ts-standardx/blob/main/__tests__/compatRules.test.ts. So far it works fine in my own projects.

As for `.prettierrc*`,

https://github.com/exuanbo/ts-standardx/blob/b3c300a20937c6ebcb2f056532d359df175a1772/src/eslintrc.ts#L10-L16

https://github.com/exuanbo/ts-standardx/blob/b3c300a20937c6ebcb2f056532d359df175a1772/src/eslintrc.ts#L21-L24

https://github.com/prettier/eslint-plugin-prettier#options says "This option will merge and override any config set with `.prettierrc` files".

It's allowed to make changes to `.prettierrc*` but the above options in `PRETTIER_STANDARD` will not be affected. The only way is changing them in `.eslintrc*`.

**Comment by xChickens** [comment]
Ah, I did not realize that's how it worked. Thank you for letting me know!

**Comment by exuanbo** [comment]
No problem. I should have added them in the documentation.

**Comment by exuanbo** [comment]
Instruction added in the `Configuration` section <https://github.com/exuanbo/ts-standardx#%EF%B8%8F-configuration>
